type Areas = {
  id: number;
  areaName: string;
  chopLocations: {
    id: number;
    areaName: string;
    location: string;
  }[];
  midweekLocations: {
    id: number;
    areaName: string;
    location: string;
  }[];
  brtLocations: {
    id: number;
    areaName: string;
    location: string;
  }[];
  freeTransportLocations: {
    id: number;
    areaName: string;
    location: string;
  }[];
  communityChurchLocations: {
    id: number;
    areaName: string;
    location: string;
  }[];
}[];

export const areas: Areas = [
  {
    id: 1,
    areaName: "Ige Daramola",
    chopLocations: [
      {
        id: 1,
        areaName: "Ige Daramola",
        location: "789 Back St, Ige Daramola",
      },
      { id: 2, areaName: "Ige Daramola", location: "123 Elm St, Ige Daramola" },
      {
        id: 3,
        areaName: "Ige Daramola",
        location: "456 Pine St, Ige Daramola",
      },
    ],
    midweekLocations: [
      {
        id: 1,
        areaName: "Ige Daramola",
        location: "789 Back St, Ige Daramola",
      },
      { id: 2, areaName: "Ige Daramola", location: "123 Elm St, Ige Daramola" },
      {
        id: 3,
        areaName: "Ige Daramola",
        location: "456 Pine St, Ige Daramola",
      },
    ],
    communityChurchLocations: [],
    brtLocations: [
      {
        id: 1,
        areaName: "Ige Daramola",
        location: "789 Back St, Ige Daramola",
      },
      { id: 2, areaName: "Ige Daramola", location: "123 Elm St, Ige Daramola" },
      {
        id: 3,
        areaName: "Ige Daramola",
        location: "456 Pine St, Ige Daramola",
      },
    ],
    freeTransportLocations: [
      {
        id: 1,
        areaName: "Ige Daramola",
        location: "789 Back St, Ige Daramola",
      },
      { id: 2, areaName: "Iyeesi", location: "123 Elm St, Iyesi" },
      { id: 3, areaName: "Obasanjo", location: "456 Pine St, Obasanjo" },
    ],
  }, //area 1

  {
    id: 2,
    areaName: "Iyesi",
    chopLocations: [
      { id: 1, areaName: "Iyesi", location: "123 Elm St, Iyesi" },
      { id: 2, areaName: "Iyesi", location: "456 Pine St, Iyesi" },
      { id: 3, areaName: "Iyesi", location: "789 Maple St, Iyesi" },
    ],
    midweekLocations: [
      { id: 1, areaName: "Iyesi", location: "123 Elm St, Iyesi" },
      { id: 2, areaName: "Iyesi", location: "456 Pine St, Iyesi" },
      { id: 3, areaName: "Iyesi", location: "789 Maple St, Iyesi" },
    ],
    communityChurchLocations: [],
    brtLocations: [
      { id: 1, areaName: "Iyesi", location: "123 Elm St, Iyesi" },
      { id: 2, areaName: "Iyesi", location: "456 PineSt, Iyesi" },
      { id: 3, areaName: "Iyesi", location: "789 Maple St, Iyesi" },
    ],
    freeTransportLocations: [
      { id: 1, areaName: "Iyesi", location: " BABA MONDAY JUNCTION EGAN ROAD" },
    ],
  }, //area 2

  {
    id: 3,
    areaName: "Obasanjo",
    chopLocations: [],
    communityChurchLocations: [],
    midweekLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  }, //area 3

  {
    id: 4,
    areaName: "Oju Ore",
    chopLocations: [],
    midweekLocations: [],
    brtLocations: [],
    communityChurchLocations: [],
    freeTransportLocations: [
      {
        id: 1,
        areaName: "Oju Ore",
        location: "TRANSFORMER, SURULERE ABULE EWUPE",
      },
      {
        id: 2,
        areaName: "Oju Ore",
        location: "4 AKINPELU STREET, OFF OKOOSI, FADINA, OJU ORE",
      },
      {
        id: 3,
        areaName: "Oju Ore",
        location: "SEGUN BLOCK JUNCTION,EWUPE ROAD,OJU ORE",
      },
      { id: 4, areaName: "Oju Ore", location: "PREM JUNCTION, OLUGBA VILLAGE" },
      {
        id: 5,
        areaName: "Oju Ore",
        location: "OTITOLOJU BLOCK, PALM ESTATE,ILOGBO",
      },
      {
        id: 6,
        areaName: "Oju Ore",
        location: "BAYO BLOCK JUNCTION, BAYO BLOCK, OJU ORE",
      },
      { id: 7, areaName: "Oju Ore", location: "103, ABE IGI, EWUPE ROAD" },
      {
        id: 8,
        areaName: "Oju Ore",
        location:
          "1, ONIWON ESTATE,BESIDE ONIWON TRANSFORMER, OFF ILOGBO ROAD,ONIWON, OJU ORE",
      },
    ],
  }, //area 4
  {
    id: 5,
    areaName: "Raji-Oba",
    chopLocations: [],
    midweekLocations: [],
    brtLocations: [],
    communityChurchLocations: [],
    freeTransportLocations: [
      {
        id: 1,
        areaName: "Raji-Oba",
        location: "38 RAJI OBA STREET ALIMOSHO",
      },
      {
        id: 2,
        areaName: "Raji-Oba",
        location: "33, ALHAJI RAMOTA STREET, EGBEDA",
      },
      {
        id: 3,
        areaName: "Raji-Oba",
        location: " 12, SOLOMON BANKOLE STREET AKOWONJO LAGOS",
      },
      {
        id: 4,
        areaName: "Raji-Oba",
        location: "7/9 MARKET LINK CLOSE AKOWONJO LAGOS",
      },
      {
        id: 5,
        areaName: "Raji-Oba",
        location: "3, ADEBOUN STREET, IYANA PAJA",
      },
      {
        id: 6,
        areaName: "Raji-Oba",
        location: "1, ADMAK CLOSE WATER B/STOP MOSAN IPAJA",
      },
      {
        id: 7,
        areaName: "Raji-Oba",
        location: "PLOT 4 B/S STREET , SHAGARI ESTATE MOSAN IPAJA",
      },
    ],
  }, //area 5
  {
    id: 6,
    areaName: "Mosan Ipaja",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 7,
    areaName: "Gowon Estate",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 8,
    areaName: "Baruwa",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 9,
    areaName: "Aboru",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 10,
    areaName: "Iyana Isashi",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 11,
    areaName: "Wilky",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 12,
    areaName: "Petro",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 13,
    areaName: "Ijaiye",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 14,
    areaName: "Ogba",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 15,
    areaName: "Yaba",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 16,
    areaName: "Mushin",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 17,
    areaName: "Amuwo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 18,
    areaName: "Ayobo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 19,
    areaName: "Olayemi",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 20,
    areaName: "Candos",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 21,
    areaName: "Majiyagbe",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 22,
    areaName: "Lafenwa",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 23,
    areaName: "Perfect Peace",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 24,
    areaName: "Anthony",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 25,
    areaName: "Akute",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 26,
    areaName: "Denro",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 27,
    areaName: "Olodi-Apapa",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 28,
    areaName: "Apapa Park-Lane",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 29,
    areaName: "Alagbado Akinde",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 30,
    areaName: "AIT",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 31,
    areaName: "Agege",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 32,
    areaName: "Fagba",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 33,
    areaName: "Atan",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 34,
    areaName: "Adelans 1",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 35,
    areaName: "Lusada",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 36,
    areaName: "Ijegun-Ikotun",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 37,
    areaName: "Igando",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 38,
    areaName: "Iyana Odo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 39,
    areaName: "Arida",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 40,
    areaName: "Shasha",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 41,
    areaName: "Egbeda",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 42,
    areaName: "Oregun-Ikeja",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 43,
    areaName: "Cement",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 44,
    areaName: "Ojodu Berger 1",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 45,
    areaName: "Ifako",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 46,
    areaName: "Isheri OPIC",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 47,
    areaName: "Ojodu Berger 2",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 48,
    areaName: "Ikosi Ketu",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 49,
    areaName: "Magodo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 50,
    areaName: "Okokomaiko",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 51,
    areaName: "Agbara",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 52,
    areaName: "Idorawa-Edu",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 53,
    areaName: "Ijuri",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 54,
    areaName: "Badagry",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 55,
    areaName: "Ibiye",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 56,
    areaName: "Okota",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 57,
    areaName: "Oshodi",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 58,
    areaName: "Festac",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 59,
    areaName: "Iju-Ishaga",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 60,
    areaName: "Emdeo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 61,
    areaName: "Agbado",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 62,
    areaName: "Bode Williams",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 63,
    areaName: "Lekki",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 64,
    areaName: "VGC",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 65,
    areaName: "Ajah",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 66,
    areaName: "Badore",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 67,
    areaName: "Surulere",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 68,
    areaName: "Lawanson",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 69,
    areaName: "Masha",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 70,
    areaName: "Ilaje",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 71,
    areaName: "Owode",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 72,
    areaName: "Sango",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 73,
    areaName: "Abebi Ota",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 74,
    areaName: "Igbala",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 75,
    areaName: "Ilogbo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 76,
    areaName: "Ijoko",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 77,
    areaName: "WhiteHouse",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 78,
    areaName: "Iyesi 2",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 79,
    areaName: "Highcourt",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 80,
    areaName: "Atan 2",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 81,
    areaName: "Adelans 2",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 82,
    areaName: "Amje",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 83,
    areaName: "Ikola Command",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 84,
    areaName: "Ejigbo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 85,
    areaName: "Ijeododo",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 86,
    areaName: "Lsdpc",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 87,
    areaName: "Ajangbadi",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 88,
    areaName: "Gbagada",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 89,
    areaName: "Ilupeju",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 90,
    areaName: "Satellite Town",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 91,
    areaName: "Ikoyi",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
  {
    id: 92,
    areaName: "Eti-Osa",
    chopLocations: [],
    midweekLocations: [],
    communityChurchLocations: [],
    brtLocations: [],
    freeTransportLocations: [],
  },
];
